contact_links:
    - name: 📄 Doks
      url: https://github.com/gethyas/doks
      about: File an issue or make an improvement to Doks.
    - name: 💁 Support
      url: https://github.com/gethyas/doks/discussions
      about: 'Get help on Doks Discussions'
